import uuid
from fastapi import HTTPException, status
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from datetime import datetime, timezone

from app.models.community import Community
from app.models.membership import Membership, MembershipStatus, MembershipRole
from app.models.user import User


def _handle_integrity_error(e: IntegrityError):
    orig = e.orig
    
    # PostgreSQL (psycopg2/psycopg3 or similar drivers expose 'diag' or 'pgcode')
    # SQLSTATE 23505 is unique_violation
    diag = getattr(orig, "diag", None)
    if diag is not None:
        constraint_name = getattr(diag, "constraint_name", None)
        if constraint_name in (
            "uq_memberships_global_active_pending",
            "uq_memberships_user_community",
        ):
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Membership request could not be processed due to a conflict."
            )
        # Other PostgreSQL constraints/errors fall through and re-raise
        raise e

    # SQLite (no structured 'diag' constraint name, relies on string parsing)
    # Check for precise column identifiers generated by SQLite.
    orig_str = str(orig)
    if "UNIQUE constraint failed: memberships.user_id, memberships.community_id" in orig_str:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Membership request could not be processed due to a conflict."
        )
    if "UNIQUE constraint failed: memberships.user_id" in orig_str:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Membership request could not be processed due to a conflict."
        )

    # For environments where driver metadata is missing but string matches PG constraints
    if "uq_memberships_global_active_pending" in orig_str or "uq_memberships_user_community" in orig_str:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Membership request could not be processed due to a conflict."
        )

    raise e

def create_membership_request(
    db: Session,
    user: User,
    community_slug: str,
    cne: str
) -> Membership:
    # Acquire user lock to serialize operations for this applicant
    db.query(User).filter(User.id == user.id).with_for_update().first()

    community = db.query(Community).filter(Community.slug == community_slug).first()
    if not community:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Community not found"
        )
        
    # Check for any active or pending membership globally
    global_conflict = db.query(Membership).filter(
        Membership.user_id == user.id,
        Membership.status.in_([MembershipStatus.PENDING, MembershipStatus.ACTIVE])
    ).first()
    
    if global_conflict:
        if global_conflict.community_id == community.id:
            if global_conflict.status == MembershipStatus.PENDING:
                raise HTTPException(
                    status_code=status.HTTP_409_CONFLICT,
                    detail="Membership request is already pending."
                )
            else:
                raise HTTPException(
                    status_code=status.HTTP_409_CONFLICT,
                    detail="User is already an active member of this community."
                )
        else:
            if global_conflict.status == MembershipStatus.PENDING:
                raise HTTPException(
                    status_code=status.HTTP_409_CONFLICT,
                    detail="You already have a pending membership request in another community. It must be resolved or withdrawn first."
                )
            else:
                raise HTTPException(
                    status_code=status.HTTP_409_CONFLICT,
                    detail="Your active membership in another community prevents another application."
                )
                
    # Check if a rejected membership exists for this community
    existing_membership = db.query(Membership).filter(
        Membership.user_id == user.id,
        Membership.community_id == community.id
    ).first()
    
    if existing_membership:
        # We know it must be REJECTED because PENDING/ACTIVE would have been caught above.
        existing_membership.status = MembershipStatus.PENDING
        existing_membership.role = MembershipRole.MEMBER
        existing_membership.cne = cne
        existing_membership.updated_at = datetime.now(timezone.utc)
        
        try:
            db.commit()
            db.refresh(existing_membership)
            return existing_membership
        except IntegrityError as e:
            db.rollback()
            _handle_integrity_error(e)
            
    # Otherwise, create a new membership
    membership = Membership(
        user_id=user.id,
        community_id=community.id,
        cne=cne,
        status=MembershipStatus.PENDING,
        role=MembershipRole.MEMBER
    )
    db.add(membership)
    try:
        db.commit()
        db.refresh(membership)
    except IntegrityError as e:
        db.rollback()
        _handle_integrity_error(e)
    return membership


def _review_membership(db: Session, community_slug: str, membership_id: str, new_status: MembershipStatus) -> Membership:
    from uuid import UUID
    try:
        m_id = UUID(membership_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Membership not found")

    # Initial read to find the user
    initial_membership = db.query(Membership).filter(Membership.id == m_id).first()
    if not initial_membership:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Membership not found")

    # Lock user row
    db.query(User).filter(User.id == initial_membership.user_id).with_for_update().first()

    community = db.query(Community).filter(Community.slug == community_slug).first()
    if not community:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Community not found")

    # Re-read membership after acquiring lock
    membership = db.query(Membership).filter(
        Membership.id == m_id,
        Membership.community_id == community.id
    ).first()

    if not membership:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Membership not found")

    if membership.status != MembershipStatus.PENDING:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Cannot change status from {membership.status.value}"
        )
        
    if new_status == MembershipStatus.ACTIVE:
        # Verify no other PENDING/ACTIVE membership exists (guarding against legacy inconsistent data)
        global_conflict = db.query(Membership).filter(
            Membership.user_id == membership.user_id,
            Membership.status.in_([MembershipStatus.PENDING, MembershipStatus.ACTIVE]),
            Membership.id != membership.id
        ).first()
        
        if global_conflict:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="User already has an active or pending membership."
            )

    membership.status = new_status
    # Ensure role is preserved as MEMBER
    membership.role = MembershipRole.MEMBER
    
    try:
        db.commit()
        db.refresh(membership)
    except IntegrityError as e:
        db.rollback()
        _handle_integrity_error(e)
        
    return membership


def approve_membership(db: Session, community_slug: str, membership_id: str) -> Membership:
    return _review_membership(db, community_slug, membership_id, MembershipStatus.ACTIVE)


def reject_membership(db: Session, community_slug: str, membership_id: str) -> Membership:
    return _review_membership(db, community_slug, membership_id, MembershipStatus.REJECTED)

from app.models.membership_permission import MembershipPermission, PermissionType
from app.schemas.membership_permission import MembershipPermissionsResponse, MembershipPermissionsUpdate

def _get_target_moderator_locked(db: Session, community_slug: str, membership_id: str) -> Membership:
    from uuid import UUID
    try:
        m_id = UUID(membership_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Membership not found")
        
    community = db.query(Community).filter(Community.slug == community_slug).first()
    if not community:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Community not found")
        
    membership = db.query(Membership).filter(
        Membership.id == m_id,
        Membership.community_id == community.id
    ).with_for_update().first()
    
    if not membership:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Membership not found")
        
    if membership.status != MembershipStatus.ACTIVE or membership.role != MembershipRole.MODERATOR:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Target is not an ACTIVE MODERATOR"
        )
        
    return membership

def get_moderator_permissions(db: Session, community_slug: str, membership_id: str) -> MembershipPermissionsResponse:
    # No lock needed for simple GET, just regular lookup
    from uuid import UUID
    try:
        m_id = UUID(membership_id)
    except ValueError:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Membership not found")
        
    community = db.query(Community).filter(Community.slug == community_slug).first()
    if not community:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Community not found")
        
    membership = db.query(Membership).filter(
        Membership.id == m_id,
        Membership.community_id == community.id
    ).first()
    
    if not membership:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Membership not found")
        
    if membership.status != MembershipStatus.ACTIVE or membership.role != MembershipRole.MODERATOR:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Target is not an ACTIVE MODERATOR"
        )
        
    grants = db.query(MembershipPermission).filter(
        MembershipPermission.membership_id == m_id
    ).all()
    
    granted_perms = {g.permission for g in grants}
    
    return MembershipPermissionsResponse(
        upload_official_documents=PermissionType.UPLOAD_OFFICIAL_DOCUMENTS in granted_perms,
        create_announcements=PermissionType.CREATE_ANNOUNCEMENTS in granted_perms,
        manage_document_voting=PermissionType.MANAGE_DOCUMENT_VOTING in granted_perms
    )

def update_moderator_permissions(db: Session, community_slug: str, membership_id: str, permissions_in: MembershipPermissionsUpdate) -> MembershipPermissionsResponse:
    membership = _get_target_moderator_locked(db, community_slug, membership_id)
    
    updates = permissions_in.model_dump(exclude_unset=True)
    
    # Process updates
    for perm_key, enabled in updates.items():
        perm_type = PermissionType[perm_key.upper()]
        
        existing = db.query(MembershipPermission).filter(
            MembershipPermission.membership_id == membership.id,
            MembershipPermission.permission == perm_type
        ).first()
        
        if enabled and not existing:
            new_grant = MembershipPermission(
                membership_id=membership.id,
                permission=perm_type
            )
            db.add(new_grant)
        elif not enabled and existing:
            db.delete(existing)
            
    db.commit()
    
    return get_moderator_permissions(db, community_slug, membership_id)

from app.schemas.membership import PendingMembershipResponse

def get_pending_memberships(db: Session, community_slug: str, skip: int = 0, limit: int = 100) -> list[PendingMembershipResponse]:
    community = db.query(Community).filter(Community.slug == community_slug).first()
    if not community:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Community not found")
        
    query = (
        db.query(Membership, User)
        .join(User, Membership.user_id == User.id)
        .filter(
            Membership.community_id == community.id,
            Membership.status == MembershipStatus.PENDING
        )
        .order_by(Membership.updated_at.asc(), Membership.id.asc())
        .offset(skip)
        .limit(limit)
        .all()
    )
    
    results = []
    for membership, user in query:
        results.append(
            PendingMembershipResponse(
                id=membership.id,
                status=membership.status,
                role=membership.role,
                cne=membership.cne,
                created_at=membership.created_at,
                updated_at=membership.updated_at,
                username=user.username,
                first_name=user.first_name,
                family_name=user.family_name
            )
        )
    return results


def withdraw_membership_request(
    db: Session,
    community_slug: str,
    membership_id: str,
    user: User
) -> None:
    try:
        m_uuid = uuid.UUID(membership_id)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Membership not found"
        )
        
    # Lock user row to serialize operations
    db.query(User).filter(User.id == user.id).with_for_update().first()
    
    community = db.query(Community).filter(Community.slug == community_slug).first()
    if not community:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Community not found"
        )

    # Read and lock the specific membership
    membership = db.query(Membership).filter(
        Membership.id == m_uuid,
        Membership.community_id == community.id,
        Membership.user_id == user.id
    ).with_for_update().first()
    
    if not membership:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Membership not found"
        )
        
    if membership.status == MembershipStatus.ACTIVE:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Membership is already active."
        )
        
    if membership.status == MembershipStatus.REJECTED:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Membership is already rejected."
        )
        
    try:
        db.delete(membership)
        db.commit()
    except Exception:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to withdraw membership request."
        )
