"""Add global active/pending membership index

Revision ID: 2b032f8c674b
Revises: 92bb2697b74d
Create Date: 2026-10-03 13:12:59.509235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b032f8c674b'
down_revision: Union[str, Sequence[str], None] = '92bb2697b74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_memberships_global_active_pending', 'memberships', ['user_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'ACTIVE')"), sqlite_where=sa.text("status IN ('PENDING', 'ACTIVE')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_memberships_global_active_pending', table_name='memberships', postgresql_where=sa.text("status IN ('PENDING', 'ACTIVE')"), sqlite_where=sa.text("status IN ('PENDING', 'ACTIVE')"))
    # ### end Alembic commands ###
