"""add_membership_permissions

Revision ID: 35fb40df73f5
Revises: 589ce55cec37
Create Date: 2026-10-03 16:49:38.363807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35fb40df73f5'
down_revision: Union[str, Sequence[str], None] = '589ce55cec37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('UPLOAD_OFFICIAL_DOCUMENTS', 'CREATE_ANNOUNCEMENTS', 'MANAGE_DOCUMENT_VOTING', name='permission_type', native_enum=False, length=50), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'permission', name='uq_membership_permissions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership_permissions')
    # ### end Alembic commands ###
