"""Add document_votes table

Revision ID: 3eeecb92fbc2
Revises: 75c1a93cb232
Create Date: 2026-10-03 12:06:28.448401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eeecb92fbc2'
down_revision: Union[str, Sequence[str], None] = '75c1a93cb232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('voter_id', sa.Uuid(), nullable=False),
    sa.Column('vote', sa.Enum('YES', 'NO', name='vote_value', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'voter_id', name='uq_document_votes_doc_voter')
    )
    op.create_index(op.f('ix_document_votes_document_id'), 'document_votes', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_votes_voter_id'), 'document_votes', ['voter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_votes_voter_id'), table_name='document_votes')
    op.drop_index(op.f('ix_document_votes_document_id'), table_name='document_votes')
    op.drop_table('document_votes')
    # ### end Alembic commands ###
