"""Add preview_path to documents

Revision ID: 92bb2697b74d
Revises: 3eeecb92fbc2
Create Date: 2026-10-03 12:29:06.457635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bb2697b74d'
down_revision: Union[str, Sequence[str], None] = '3eeecb92fbc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('preview_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'preview_path')
    # ### end Alembic commands ###
