"""add_role_to_memberships

Revision ID: 95af7394f5be
Revises: e51d75b18287
Create Date: 2026-10-01 10:02:00.503667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95af7394f5be'
down_revision: Union[str, Sequence[str], None] = 'e51d75b18287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('role', sa.Enum('MEMBER', 'DELEGATE', name='membership_role', native_enum=False, length=20), server_default='MEMBER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'role')
    # ### end Alembic commands ###
