"""Add active delegate partial index

Revision ID: b0d0b009b5e7
Revises: 35fb40df73f5
Create Date: 2026-10-03 18:18:33.768712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d0b009b5e7'
down_revision: Union[str, Sequence[str], None] = '35fb40df73f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check for multiple active delegates
    bind = op.get_bind()
    conflicts = bind.execute(sa.text("""
        SELECT community_id, COUNT(*) 
        FROM memberships 
        WHERE status = 'ACTIVE' AND role = 'DELEGATE' 
        GROUP BY community_id 
        HAVING COUNT(*) > 1
    """)).fetchall()
    
    if conflicts:
        raise Exception("Cannot apply index: Found communities with multiple active delegates.")
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_memberships_community_active_delegate', 'memberships', ['community_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE' AND role = 'DELEGATE'"), sqlite_where=sa.text("status = 'ACTIVE' AND role = 'DELEGATE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_memberships_community_active_delegate', table_name='memberships', postgresql_where=sa.text("status = 'ACTIVE' AND role = 'DELEGATE'"), sqlite_where=sa.text("status = 'ACTIVE' AND role = 'DELEGATE'"))
    # ### end Alembic commands ###
